title: RAKOTONIAINA RAJO MAMPIONONA
author: GitHub Rajo Mampionona
email: rakotoniainarajomampionona@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ceci est ma page personnel sur GitHub.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  rajo404 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
